name: CheckFormat

on:
  push:

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: clang-format
        uses: egor-tensin/clang-format@v1
