name: git-test
on:
  push:
jobs:
  test_job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: EchoTest
        run: echo "This is a test"
      - name: GitStatusStep
        run: git status && git fetch origin main
      - name: GitDiffStep
        run: git diff origin/main
